package studentmanagementpoint.views;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import studentmanagementpoint.dto.StudentModel;
import studentmanagementpoint.service.UserService;

/**
 *
 * @author Admin
 */
public class TableStudent extends javax.swing.JFrame {

    private List<StudentModel> students;

    /**
     * Creates new form TableStudent
     */
    public TableStudent(List<StudentModel> students) {
        this.students = students;
        initComponents();
        setSizeColumn();
        loadDataToTable();

    }

    public TableStudent() {
        initComponents();
    }

    private void setSizeColumn() {
        tableListStudent.getColumnModel().getColumn(0).setPreferredWidth(50); // STT
        tableListStudent.getColumnModel().getColumn(1).setPreferredWidth(110); // Mã SV
        tableListStudent.getColumnModel().getColumn(2).setPreferredWidth(180); // Họ và Tên
        tableListStudent.getColumnModel().getColumn(3).setPreferredWidth(70); // Giới tính
        tableListStudent.getColumnModel().getColumn(4).setPreferredWidth(100); // Ngày sinh
        tableListStudent.getColumnModel().getColumn(5).setPreferredWidth(50); // Lớp
        tableListStudent.getColumnModel().getColumn(6).setPreferredWidth(180); // Khoa
        tableListStudent.getColumnModel().getColumn(7).setPreferredWidth(200); // Địa chỉ
    }

    public void loadDataToTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tableListStudent.getModel();
        tableModel.setRowCount(0);

        int currentIndex = 1;
        for (StudentModel u : students) {
            tableModel.addRow(new Object[]{
                currentIndex++,
                u.getStudentId(),
                u.getName(),
                u.getGender(),
                u.getDob(),
                UserService.getNameByClassId(u.getClassId()),
                u.getDepartment(),
                u.getAddress()
            });
        }
        tableListStudent.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableListStudent = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableListStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Sinh Viên", "Họ và Tên", "Giới tính", "Ngày sinh", "Lớp", "Ngành ", "Quê quán"
            }
        ));
        jScrollPane1.setViewportView(tableListStudent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListStudent;
    // End of variables declaration//GEN-END:variables
}
